DROP TYPE wheel_drive CASCADE;
DROP TYPE steering_wheel CASCADE;

DROP FUNCTION IF EXISTS update_updated_at_column CASCADE;
DROP TRIGGER IF EXISTS set_timestamp_cars ON cars;
DROP TRIGGER IF EXISTS set_timestamp_users ON users;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS cars CASCADE;
DROP TABLE IF EXISTS car_photos CASCADE;
DROP TABLE IF EXISTS bodies CASCADE;
DROP TABLE IF EXISTS brands CASCADE;
DROP TABLE IF EXISTS colors CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS generations CASCADE;
