// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Body struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Brand struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Car struct {
	ID               string      `json:"id"`
	User             *User       `json:"user"`
	Category         *Category   `json:"category"`
	Brand            *Brand      `json:"brand"`
	Color            *Color      `json:"color"`
	Generation       *Generation `json:"generation"`
	Body             *Body       `json:"body"`
	City             *City       `json:"city"`
	Model            *Model      `json:"model"`
	AvatarSource     *string     `json:"avatarSource,omitempty"`
	EngineVolume     *string     `json:"engineVolume,omitempty"`
	Mileage          *string     `json:"mileage,omitempty"`
	WheelDrive       *string     `json:"wheelDrive,omitempty"`
	SteeringWheel    *string     `json:"steeringWheel,omitempty"`
	CustomsClearance *bool       `json:"customsClearance,omitempty"`
	Description      *string     `json:"description,omitempty"`
	Price            *string     `json:"price,omitempty"`
	CreatedAt        *string     `json:"createdAt,omitempty"`
	UpdatedAt        *string     `json:"updatedAt,omitempty"`
}

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type City struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Color struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Generation struct {
	ID      string `json:"id"`
	ModelID string `json:"modelId"`
	Name    string `json:"name"`
}

type Model struct {
	ID      string `json:"id"`
	BrandID string `json:"brandId"`
	Name    string `json:"name"`
}

type Query struct {
}

type User struct {
	ID          string  `json:"id"`
	PhoneNumber string  `json:"phoneNumber"`
	Username    *string `json:"username,omitempty"`
	BankCard    *string `json:"bankCard,omitempty"`
	Email       string  `json:"email"`
}
