basePath: /api
definitions:
  transport.errorResponse:
    properties:
      message:
        type: string
    type: object
  transport.successResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
host: kolesaapi.onrender.com
info:
  contact: {}
  description: This is a sample server celler server.
  title: Kolesa API
  version: "1.0"
paths:
  /cars:
    get:
      consumes:
      - application/json
      description: Get basic info
      parameters:
      - description: Limit param
        in: query
        name: limit
        type: integer
      - description: Offset param
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.successResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.errorResponse'
      summary: Main page cars
      tags:
      - cars
  /cars/{id}:
    get:
      consumes:
      - application/json
      description: Get info about one car by id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.successResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.errorResponse'
      summary: Get info about car
      tags:
      - cars
  /cars/extended:
    get:
      consumes:
      - application/json
      description: Get all cars
      parameters:
      - description: Limit param
        in: query
        name: limit
        type: integer
      - description: Offset param
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.successResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.errorResponse'
      summary: Get all cars
      tags:
      - cars
  /cars/photo/{file_id}:
    get:
      description: Get car avatar by fileId from S3
      parameters:
      - description: ID файла
        in: path
        name: fileId
        required: true
        type: string
      produces:
      - image/png
      - ' image/jpeg'
      responses:
        "200":
          description: OK
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.errorResponse'
      summary: Get car avatar
      tags:
      - cars
  /s3/auth_token:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.successResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.errorResponse'
      summary: Get S3 auth token
      tags:
      - s3
swagger: "2.0"
