basePath: /api
definitions:
  transport.errorResponse:
    properties:
      message:
        type: string
    type: object
  transport.successResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a sample server celler server.
  title: Kolesa API
  version: "1.0"
paths:
  /cars:
    get:
      description: Deleting a specific car
      parameters:
      - description: Deleting car id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.successResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/transport.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.errorResponse'
      summary: Delete car by id
      tags:
      - cars
  /cars/photo/{fileId}:
    get:
      description: Get car avatar by fileId from S3
      parameters:
      - description: ID файла
        in: path
        name: fileId
        required: true
        type: string
      produces:
      - image/png
      - ' image/jpeg'
      responses:
        "200":
          description: OK
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.errorResponse'
      summary: Get car avatar
      tags:
      - cars
swagger: "2.0"
